### PR TITLE
Bump Spring Boot 2.7.0

### PR DESCRIPTION
**Pull request by zorglube**

### CODE REVIEW

**Comment by zorglube** [comment]
Feel free to refuse part of the PR and to tell me what you don't like.

**Comment by lbruun** [comment]
Hi @zorglube. Thank you for our PR.

I think you've (accidentally?) reformatted a lot - if not all - of the source code files. This makes it hard to tell what your real intention is. Also the reformatting in itself is not for the better. For example, all indentions within  comment sections has been removed by your formatter.

Just a hint: When contributing to FOSS projects you generally have to accept whatever code formatting convention is already used. The only way maintainers of such project would accept a PR which changes code formatting would be if you are correcting an inconsistency (for example one file not being formatted the same way as the other files in the project). 

I hope this hasn't put you off from contributing again. You are most welcome.

**Comment by lbruun** [comment]
Btw:  I've tested the existing version `1.1.1` with Spring Boot 2.7. It works fine.

I would think it is better to keep the deps for PreLiquibase at a conservative level, i.e. be one or two minor versions _behind_ the currently released version of Spring Boot. At the moment PreLiquibase has a POM which uses Spring Boot 2.5 which means it is usable with Spring Boot 2.5, 2.6 and 2.7.

**Comment by zorglube** [comment]
> Hi @zorglube. Thank you for our PR.
> 
> I think you've (accidentally?) reformatted a lot - if not all - of the source code files. This makes it hard to tell what your real intention is. Also the reformatting in itself is not for the better. For example, all indentions within comment sections has been removed by your formatter.

I'll manage that, by the way, do you have a `fomatter.xml` that you can add to the project ? 
> 
> Just a hint: When contributing to FOSS projects you generally have to accept whatever code formatting convention is already used. The only way maintainers of such project would accept a PR which changes code formatting would be if you are correcting an inconsistency (for example one file not being formatted the same way as the other files in the project).

Yes you're right. 
> 
> I hope this hasn't put you off from contributing again. You are most welcome.

No don't worry ;-)

**Comment by lbruun** [comment]
Closing this one as support for Spring Boot 2.7 is already present.

**Comment by zorglube** [comment]
Don't you want to move to JUnit 5 ? It was also included in this PR.

**Comment by lbruun** [comment]
> Don't you want to move to JUnit 5 ? It was also included in this PR.

It is already at JUnit 5.

**Comment by zorglube** [comment]
How ok, I missed that, sorry.

**Pull request closed without merging**
