### PR TITLE
Improved `Resource` loading

### PR DESCRIPTION
**Pull request by zorglube**

### CODE REVIEW

**Comment by lbruun** [comment]
Not sure I understand the idea here.  If the idea is - disregarding formatting changes - that `sqlScriptReferences` should be of type `List<Resource>` instead of type `List<String>` then I'm not sure that is possible. With the changes introduced in v1.2 the value can now include "folder references", such a `classpath:foo/bar/`.  Haven't tested, but I'm not sure that such value is formally a valid Spring Resource literal? (a folder is not really a resource, it is just a place where resources live).

**Comment by zorglube** [comment]
The Spring Resources is a way to let the user free to use `classpath:`, `file:`, even `http:` resource, and forme the developer point of view, it's just a Resource whatever the real origin. 

I'll have a look to rebase the branche on master.

**Comment by lbruun** [comment]
> The Spring Resources is a way to let the user free to use `classpath:`, `file:`, even `http:` resource, and forme the developer point of view, it's just a Resource whatever the real origin.
> 
> I.e.: Resource can be `classpath:foo/bar.sql` or `file:/temp/foo/bar.sql`
> 

Sure, but see [How the module locates SQL script files](https://github.com/lbruun/Pre-Liquibase#how-the-module-locates-sql-script-files) for more information about the values now allowed for `sqlScriptReferences`.

Spring Resource is a clever abstraction, but their downside is - AFAIK - that they must point to an _actual_ object, not a folder. They must point to something which is "loadable".  Therefore, formally, a literal such as `classpath:preliquibase/` is not really a Spring Resource although it looks like one. This is why I think we need to keep the type as `List<String>`.

**Comment by zorglube** [comment]
I get your point. 

I'll search a bit for that. I wrote that code few weeks ago. I'm not totally sure, but I guess a Ressource can be a directory.

**Comment by zorglube** [comment]
@lbruun : I'm working on the solution to load all files from a directory with `Resources`.

**Comment by zorglube** [comment]
> @lbruun : I'm working on the solution to load all files from a directory with `Resources`.

@lbruun : I found a solution, you'll tell me.

**Comment by lbruun** [comment]
This PR needs to be re-based so that it only proposes one logical change. At the moment this PR includes many other changes than what is proposes to change/improve.

It also needs a justification: For example: In what way does it improve either the experience for those using Pre-Liquibase or make the Pre-Liqiubase source code easier to maintain.

Not opposed to change at all. Just need to understand what the change is (in isolation) and what it brings to the table.
Thx.

**Comment by zorglube** [comment]
Close in the benefit of : https://github.com/lbruun/Pre-Liquibase/pull/19

**Pull request closed without merging**
